Pokiiio 02ArduinoSetting
Nefry-Community/TutorialBook pull request #17
Opened 2018-03-02 16:22 UTC by pokiiio

一旦PRを投げさせていただきます、ご査収ください。

2018-03-03 04:16 UTC, wamisnet approved these changes

2018-03-03 04:17 UTC, wamisnet commented
よいと思います！
改行があった方がいい場所等あるかと思いますが、そのあたりのやり方はちゃんとくさんに一任したいと思っています。

2018-03-03 04:20 UTC, wamisnet commented
現状Mac版しか情報がないのでそのあたりWindowsのインストール手順等追加が必要かと思いますが、ぽきおさんの方でいけますかね？
一応Windows版の参考サイトのリンクをつけておきます
http://nefry.studio/ArduinoIDE%E3%81%AE%E7%92%B0%E5%A2%83%E3%82%92%E6%95%B4%E3%81%88%E3%82%88%E3%81%86/

2018-03-03 04:22 UTC, wamisnet commented
@pokiiio  一度このプルリクはマージした上でWindows版の追加等の対応した上で再度プルリクでちゃんとくさんレビューに入る感じでいかがでしょうか？

2018-03-04 12:55 UTC, pokiiio commented
ごめんなさい、すっかり忘れてました。
Windowsのインストールに関して追記しますのでMergeはお待ち下さい。

2018-03-04 14:48 UTC, pokiiio commented
更新しました🍖

2018-03-04 17:12 UTC, wamisnet commented
ありがとうございます！
いろんなインストール方法をありがとうございます！逆にどの方法でインストールすればいいのかわからなくなりそうなので、tipsみたいなカラムを分けれるとよいかなと思います。

2018-03-04 17:13 UTC, wamisnet commented
基本的に問題ないと思うのでちゃんとくさんのレビューに回したいと思います。

2018-03-10 07:17 UTC, tokutoku393 requested changes

2018-03-10 07:17 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
>  このページでは、Arduino IDEにNefry BTの開発環境をインストールする方法を紹介します。@<strong>{Arduino IDEでNefry BTの開発をする際に必須になる項目です。}
「このページでは」->「この章では」

2018-03-10 07:17 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
>  このページでは、Arduino IDEにNefry BTの開発環境をインストールする方法を紹介します。@<strong>{Arduino IDEでNefry BTの開発をする際に必須になる項目です。}
「Arduino IDEでNefry BTの開発をする際に必須になる項目です。」
↓
「Nefry BTの開発にはArduino IDEという無料のソフトウェアが必要ですので、この手順から始めてください、」

2018-03-10 07:17 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
> +=== 起動してみましょう
「起動してみましょう」->「起動してみる」

2018-03-10 07:17 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
> + * パッチバージョン - バグ修正など
ここ、画像があるとわかりやすいかもです…（別途言及します）

2018-03-10 07:17 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
> +例えば@<tt>{v1.2.3}の場合、最初の1がメジャーバージョン、次の2がマイナーバージョン、最後の3がパッチバージョンとしています。また、 LTS(安定)版と開発版を分けていて、マイナーバージョンが偶数か奇数かで分けています。LTSがv1.2系、開発版がv1.1系などとなります。その次はLTSが1.4系、開発版がv1.3系となり、以降も偶数と奇数でのアップデートとなります。更新についてはN
「例えばv1.2.3の場合、最初の1がメジャーバージョン、次の2がマイナーバージョン、最後の3がパッチバージョンとしています。（改段落）」
「LTS(安定)版と開発版を分けていて、マイナーバージョンが偶数か奇数かで分けています。LTSがv1.2系、開発版がv1.1系などとなります。その次はLTSが1.4系、開発版がv1.3系となり、以降も偶数と奇数でのアップデートとなります。」（追記）「基本的にはLTS版を使うようにしてください。（改段落）」
「更新についてはNefryのGitHubページ（https://github.com/Nefry-Community/arduino-esp32/）にあるリリースノートに記載がありますので、参考にしてみて下さい。」

2018-03-10 07:17 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
> +Nefry BT R2以降は@<tt>{Nefry BT R2}を選択しましょう。
「Nefry BT R2以降はNefry BT R2を選択しましょう。」
↓
「お手持ちのボードのリビジョンに合わせて選択しましょう。」

2018-03-10 07:17 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
== 3.6 Neryボードのバージョンを確認
「Nefryボードがお手元に届いたら、まずはバージョンを確認しましょう！」

2018-03-10 07:17 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
> +ちなみに、Nefry v2（https://dotstud.io/shop/nefry-connect-internet/）というボードも存在するので区別するために、VersionではなくRevisionとしました。
Nefry BTには無印のもの（R1）とR2が存在します（2018年1月現在）。

Nefryボードには、初期NefryやNefry v2.0（https://dotstud.io/shop/nefry-connect-internet/）というバージョンも存在するので、BT内ではRevisionで分類しています。

2018-03-10 07:17 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
> +基本的な使い方に代わりはないですが、 書き込み時のボード選択でR2の場合は@<tt>{Nefry BT R2}を選択し、無印の場合は@<tt>{Nefry BT}を選択して書き込みをして下さい。
直近でR3が出る予定なので、「お手持ちのボードの背面でRevision番号を確認してください。表記のないものは無印となります。」にとどめてください…。

2018-03-10 07:17 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
> +次は、はじめてのプログラム書き込みの例としてNefry BT付属のLEDでLチカを試してみてください。
「次は、はじめてのプログラム書き込みの例としてNefry BT付属のLEDでLチカを試してみてください。」
↓
「次は、Nefry BTへのプログラムの書き込みを試してみましょう。」

2018-03-10 07:20 UTC, tokutoku393 requested changes

2018-03-10 07:20 UTC, tokutoku393 commented on articles/02ArduinoSetting.re
> +
（追加）今回は、インストーラーをダウンロードする方法を紹介します。

2018-03-10 13:30 UTC, pokiiio commented on articles/02ArduinoSetting.re
>  このページでは、Arduino IDEにNefry BTの開発環境をインストールする方法を紹介します。@<strong>{Arduino IDEでNefry BTの開発をする際に必須になる項目です。}
たいおうしました！

2018-03-10 13:31 UTC, pokiiio commented on articles/02ArduinoSetting.re
> +=== 起動してみましょう
たいおうしました！

2018-03-10 13:31 UTC, pokiiio commented on articles/02ArduinoSetting.re
> + * パッチバージョン - バグ修正など
画像追加しました！
コミットしましたが、イメージと合ってるかご確認いただきたく！

2018-03-10 13:32 UTC, pokiiio commented on articles/02ArduinoSetting.re
> +例えば@<tt>{v1.2.3}の場合、最初の1がメジャーバージョン、次の2がマイナーバージョン、最後の3がパッチバージョンとしています。また、 LTS(安定)版と開発版を分けていて、マイナーバージョンが偶数か奇数かで分けています。LTSがv1.2系、開発版がv1.1系などとなります。その次はLTSが1.4系、開発版がv1.3系となり、以降も偶数と奇数でのアップデートとなります。更新についてはN
たいおうしました！

2018-03-10 13:32 UTC, pokiiio commented on articles/02ArduinoSetting.re
> +Nefry BT R2以降は@<tt>{Nefry BT R2}を選択しましょう。
たいおうしました！

2018-03-10 13:32 UTC, pokiiio commented on articles/02ArduinoSetting.re
たいおうしました！

2018-03-10 13:32 UTC, pokiiio commented on articles/02ArduinoSetting.re
> +ちなみに、Nefry v2（https://dotstud.io/shop/nefry-connect-internet/）というボードも存在するので区別するために、VersionではなくRevisionとしました。
たいおうしました！

2018-03-10 13:32 UTC, pokiiio commented on articles/02ArduinoSetting.re
> +基本的な使い方に代わりはないですが、 書き込み時のボード選択でR2の場合は@<tt>{Nefry BT R2}を選択し、無印の場合は@<tt>{Nefry BT}を選択して書き込みをして下さい。
たいおうしました！

2018-03-10 13:32 UTC, pokiiio commented on articles/02ArduinoSetting.re
> +次は、はじめてのプログラム書き込みの例としてNefry BT付属のLEDでLチカを試してみてください。
たいおうしました！

2018-03-10 13:32 UTC, pokiiio commented on articles/02ArduinoSetting.re
> +
たいおうしました！

2018-03-10 13:34 UTC, pokiiio commented
諸々たいおうしました！
developの更新もmergeしました！
ご確認のほどよろしくお願いします！

2018-04-07 03:32 UTC, merged