04DefaultSW 執筆初動
Nefry-Community/TutorialBook pull request #23
Opened 2018-03-07 10:36 UTC by 1ft-seabass

04DefaultSW 執筆いったんやってみました。

2018-03-10 06:23 UTC, tokutoku393 requested changes
最初のレビューなので、トンマナ統一のためかなり細くなってしまいました、、。今後の調整も含め、確認でお願いします！

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +このページではNefry BTに標準で取り付けられているスイッチを操作すると前章の内蔵フルカラーLEDのカラーが変化する仕組みを説明します。
「この章では、Nefry BTに標準で取り付けられているスイッチの扱い方を紹介します。今回はスイッチを押したら前章の内蔵フルカラーLEDのカラーが変化する仕組みを試してみます。」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +このページではNefry BTに標準で取り付けられているスイッチを操作すると前章の内蔵フルカラーLEDのカラーが変化する仕組みを説明します。
メインはスイッチの説明、付随でLEDの操作なのでこういう書き方がいいかなと思いました！

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +今回あつかうスイッチの位置を確認します。
「あつかう」->「扱う」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +
「このようにUSB接続口に近いところに両サイドにスイッチがあるうちの、**「SW」と刻印された方がスイッチ**です。「Reset」とある方はNefryを再起動するスイッチです。」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +このSWと刻印されたスイッチの反応をプログラムで分かるようにして、フルカラーLEDのカラーが変化するようにします。
「このSWと刻印されたスイッチの反応をプログラムで分かるようにして、フルカラーLEDのカラーが変化するようにします。」
↓
「このSWと刻印されたスイッチ（以下「SWスイッチ」）の反応をプログラムで分かるようにして、スイッチを押すとフルカラーLEDのカラーが変化するようにします。」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +== Nefry BTをPCのUSBポートにさしてください。
ここから

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
>  初期状態で書かれている現状のコードを削除して、次のコードに差し替えましょう。
ここまで、本の最初の方の章にまとめてしまってもよさそうです

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +このコードは https://github.com/Nefry-Community/TutorialExample/tree/master/examples にある、 04DefaultSW のサンプルからコピーペーストすることが可能です。
「コピーペースト」->「コピー＆ペースト」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
>  初期状態で書かれている現状のコードを削除して、次のコードに差し替えましょう。
次のコードに差し替えましょうの下に、先に（画面ではなく）コードが合った方がわかりやすいかもです。

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +コメントで事足りているかも？
説明、あった方が親切かと思います！

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +@<tt>{Nefry.enableSW();} によってSW有効化、つまりSWスイッチをつかうよという宣言をします。 @<tt>{Nefry.setLed(255, 255, 255);} 起動したときにフルカラーLEDが白に光ることで、プログラムが動き出したことを示しています。
「Nefry.enableSW(); によってSW有効化、つまりSWスイッチをつかうよという宣言をします。 Nefry.setLed(255, 255, 255); 起動したときにフルカラーLEDが白に光ることで、プログラムが動き出したことを示しています。」
↓
「Nefry.enableSW(); によってSW有効化、つまりSWスイッチを使うよという宣言をします。 起動したときにプログラムが動き出したことを示すため、Nefry.setLED(255, 255, 255) でフルカラーLEDを白に光らせます。（R・G・Bが全て255だと白になります。）」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +つづいて、普段待っているときのループ部分の説明です。SWスイッチを押した時を判定するのは @<tt>{Nefry.readSW()} をif文で判定することで実現しています。
「つづいて」->「続いて」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +つづいて、普段待っているときのループ部分の説明です。SWスイッチを押した時を判定するのは @<tt>{Nefry.readSW()} をif文で判定することで実現しています。
「SWスイッチを押した時を判定するのは Nefry.readSW() をif文で判定することで実現しています。」
↓
「Nefry.readSW() でSWスイッチの状態を取得することができます。」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +@<strong>{ボタンを押したあとに離したタイミング} で @<tt>{Nefry.readSW()} が1を返すので「ボタンを押した」と判定できます。そのときに、 @<tt>{Nefry.setLed(255, 0, 0);} LEDが赤に光り、 @<tt>{Nefry.ndelay(1000);} で1秒つつづいたあと、 @<tt>{Nefry.setLed(0, 0, 255);} 青
「ボタンを押したあとに離したタイミングで Nefry.readSW() が1を返すので「ボタンを押した」と判定できます。」
↓
「ボタンを押したあとに離したタイミングで Nefry.readSW() が1を返すので「ボタンを押した」と判定できます。if (Nefry.readSW() ==  1)となりますが、プログラム内では1になること（true, falseのうちtrueなこと）を省略できるので if (Nefry.readSW())で判定することができます。」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
> +@<strong>{ボタンを押したあとに離したタイミング} で @<tt>{Nefry.readSW()} が1を返すので「ボタンを押した」と判定できます。そのときに、 @<tt>{Nefry.setLed(255, 0, 0);} LEDが赤に光り、 @<tt>{Nefry.ndelay(1000);} で1秒つつづいたあと、 @<tt>{Nefry.setLed(0, 0, 255);} 青
「そのときに、 Nefry.setLed(255, 0, 0); LEDが赤に光り、 Nefry.ndelay(1000); で1秒つつづいたあと、 Nefry.setLed(0, 0, 255); 青に戻ります。」
↓
「（改段落）そのときに、Nefry.setLed(255, 0, 0); でLEDを赤に光らせ、 Nefry.ndelay(1000); で1秒続いたあと、Nefry.setLed(0, 0, 255); で青に戻します。」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/04DefaultSW.re
>  == プログラムの保存とボードに書き込み
ここの項目も、まとめていいかもですね

2018-03-10 06:23 UTC, tokutoku393 commented on articles/03DefaultLed.re
> +このページでは内蔵フルカラーLEDを操作する方法を仕組みを説明します。
「このページでは」->「この章では」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/03DefaultLed.re
>  == プログラムの書き込み
ここから

2018-03-10 06:23 UTC, tokutoku393 commented on articles/03DefaultLed.re
>  初期状態で書かれている現状のコードを削除して、次のコードに差し替えましょう。
ここまで

2018-03-10 06:23 UTC, tokutoku393 commented on articles/03DefaultLed.re
> +このコードは https://github.com/Nefry-Community/TutorialExample/tree/master/examples にある、 03DefaultLed のサンプルからコピーペーストすることが可能です。
「コピーペースト」->「コピー＆ペースト」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/03DefaultLed.re
> +まず、 @<tt>{#include <Nefry.h>} によってNefry BTの今回のフルカラーLEDの制御も含めていろいろな機能を使えるようになります。
「まず、 #include <Nefry.h> によってNefry BTの今回のフルカラーLEDの制御も含めていろいろな機能を使えるようになります。」
↓
「まず、 #include <Nefry.h> によってNefry向けのライブラリを読み込んでいます。今回のフルカラーLEDの制御も含めていろいろな機能を使えるようになります。」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/03DefaultLed.re
> +まず、 @<tt>{int red,green,blue;} とすることで、フルカラーLEDの色要素（赤 red,緑 green,青 blue）をいれる値の箱（変数）をつくります。
「まず、NefryではNefry.setLED(R, G, B)という関数でRGB（赤・青・緑）要素をそれぞれ指定できるので、int red, green, blue; でそれぞれを入れる値の箱を作ります。」

2018-03-10 06:23 UTC, tokutoku393 commented on articles/03DefaultLed.re
> +まず、 @<tt>{int red,green,blue;} とすることで、フルカラーLEDの色要素（赤 red,緑 green,青 blue）をいれる値の箱（変数）をつくります。
「このあと、フルカラーLEDの色を実際に指定するために、フルカラーLEDの赤要素なら redという名前の値の箱（変数）、変数 green ならフルカラーLEDの緑要素を、変数 blue ならフルカラーLEDの青要素を入れています。

2018-03-10 06:23 UTC, tokutoku393 commented on articles/03DefaultLed.re
>  == プログラムの保存とボードに書き込み
省略してよさそう

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
> +コメントで事足りているかも？
ありがとうございます！それでいきます！

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
> +このコードは https://github.com/Nefry-Community/TutorialExample/tree/master/examples にある、 04DefaultSW のサンプルからコピーペーストすることが可能です。
了解です！

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
>  初期状態で書かれている現状のコードを削除して、次のコードに差し替えましょう。
そうですね。コードはURLで流しつつ、削除します。本の最初の方の章に、基本的なプログラムの書き方間は任せるようにします。

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
> +== Nefry BTをPCのUSBポートにさしてください。
OK

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
> +このSWと刻印されたスイッチの反応をプログラムで分かるようにして、フルカラーLEDのカラーが変化するようにします。
そのように反映します。（以下「SWスイッチ」）の流し方いいですね。

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
> +
たしかに、Resetも気になりますし入れましょう。

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
> +今回あつかうスイッチの位置を確認します。
了解です！

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
> +このページではNefry BTに標準で取り付けられているスイッチを操作すると前章の内蔵フルカラーLEDのカラーが変化する仕組みを説明します。
よいとおもいます！ありがとうございます！

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
> +@<tt>{Nefry.enableSW();} によってSW有効化、つまりSWスイッチをつかうよという宣言をします。 @<tt>{Nefry.setLed(255, 255, 255);} 起動したときにフルカラーLEDが白に光ることで、プログラムが動き出したことを示しています。
了解です！

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
> +@<strong>{ボタンを押したあとに離したタイミング} で @<tt>{Nefry.readSW()} が1を返すので「ボタンを押した」と判定できます。そのときに、 @<tt>{Nefry.setLed(255, 0, 0);} LEDが赤に光り、 @<tt>{Nefry.ndelay(1000);} で1秒つつづいたあと、 @<tt>{Nefry.setLed(0, 0, 255);} 青
了解です。

2018-03-10 14:45 UTC, 1ft-seabass commented on articles/04DefaultSW.re
>  == プログラムの保存とボードに書き込み
ですね。削除します。

2018-03-11 02:35 UTC, 1ft-seabass commented on articles/03DefaultLed.re
> +このページでは内蔵フルカラーLEDを操作する方法を仕組みを説明します。
対応します！

2018-03-11 02:35 UTC, 1ft-seabass commented on articles/03DefaultLed.re
> +このコードは https://github.com/Nefry-Community/TutorialExample/tree/master/examples にある、 03DefaultLed のサンプルからコピーペーストすることが可能です。
対応します！

2018-03-11 02:35 UTC, 1ft-seabass commented on articles/03DefaultLed.re
> +まず、 @<tt>{#include <Nefry.h>} によってNefry BTの今回のフルカラーLEDの制御も含めていろいろな機能を使えるようになります。
対応します！

2018-03-11 02:35 UTC, 1ft-seabass commented on articles/03DefaultLed.re
> +まず、 @<tt>{int red,green,blue;} とすることで、フルカラーLEDの色要素（赤 red,緑 green,青 blue）をいれる値の箱（変数）をつくります。
対応します！

2018-03-11 02:37 UTC, 1ft-seabass commented on articles/03DefaultLed.re
>  == プログラムの保存とボードに書き込み
省略します。

2018-03-11 03:00 UTC, 1ft-seabass commented
@tokutoku393 03 , 04 修正したのでご確認お願いします～

2018-04-07 03:33 UTC, merged