Nefryのプログラムの書き方
Nefry-Community/TutorialBook pull request #26
Opened 2018-03-10 08:59 UTC by tokutoku393

レビューおねがいします！！

2018-03-11 06:45 UTC, wamisnet requested changes

2018-03-11 06:45 UTC, wamisnet commented on articles/02NefryProgram.re
> +次のようなウインドウが表示されます。
いきなり「次のような」というより、「Arduino IDEを起動させると、次のような」という方がわかりやすいと思いますがいかがでしょうか？

2018-03-11 06:45 UTC, wamisnet commented on articles/02NefryProgram.re
> +@<tt>{void setup()} 内に起動時に実行したいプログラムを、@<tt>{void loop()} 内に起動中実行したいプログラムを記述していきます。
ここの説明は次の実際にプログラムを書く段階で説明した方がよいかと思います

2018-03-11 06:45 UTC, wamisnet commented on articles/02NefryProgram.re
> +Nefry BTをPCのUSBポートにさしてください。Arduino IDEでシリアルポートの選択をします。
@<chap>{02ArduinoSetting} でセットアップしたNefry BTをUSBポートに差してください。の方が親切だと思います。

2018-03-11 06:45 UTC, wamisnet commented on articles/02NefryProgram.re
> +//image[image2][プログラムのファイルを名前をつけて保存]{
画像のタイトルが下とごっちゃになってます。
画像ですが、✔と→を何かで囲ってあげた方がいいかもしれません。

2018-03-11 06:45 UTC, wamisnet commented on articles/02NefryProgram.re
> +//image[image3][02NefryProgram]{
上の画像とタイトルが逆なのでは？

2018-03-11 06:45 UTC, wamisnet commented on articles/02NefryProgram.re
> +前章を参考に、NefryのWebコンソールを開きます。「Upload Sketch」を選択します。
チュートリアル本でやる内容ではないので、できるという情報だけでいいかなと思います。
Web側に誘導するリンク情報を追加して対応しませんか？

2018-03-11 06:45 UTC, wamisnet commented on articles/02NefryProgram.re
> +メニューの @<tt>{ツール} > @<tt>{シリアルポート} > @<tt>{/dev/cu.usbserial-xxxxxx} を選択します。環境によっては @<tt>{/dev/tty.usbserial-xxxxxx} などの場合もあります。
下のアップロードする方ではメニュー画面が出てるので、こっちも画像を追加した方がいいと思います。
Windowsの画像が必要であれば言ってください。

2018-03-11 06:45 UTC, wamisnet commented on articles/02NefryProgram.re
> +メニューの @<tt>{ツール} > @<tt>{シリアルポート} > @<tt>{COMxx} （xxの部分はNefryBTが挿してあるCOMポート） を選択します。
NefryBT→Nefry BT

2018-03-11 07:54 UTC, pokiiio approved these changes
基本的には 🆗 です！

2018-03-11 07:54 UTC, pokiiio commented on articles/02NefryProgram.re
> +Webコンソールからのアップデートは、Nefryを直接PCへさせない場合などに活用してください。
MUSTではないですが、`NefryがPCで認識できないとき`みたいなケースも書いて頂けるとベターかなと。

2018-03-12 11:01 UTC, 1ft-seabass approved these changes
OK　ぜんぜんいいとおもう！

2018-04-07 04:00 UTC, merged