メンバー紹介
Nefry-Community/TutorialBook pull request #29
Opened 2018-03-11 06:05 UTC by wamisnet

自分の紹介が問題ないか確認してレビューを許可してください

2018-03-11 06:07 UTC, 1ft-seabass approved these changes
OKです！

2018-03-11 07:34 UTC, pokiiio approved these changes
ボールド体になってて素敵です！

2018-03-13 16:33 UTC, pokiiio requested changes
あ、`ぽきお`はカタカナでもいいですか？

2018-03-14 15:15 UTC, pokiiio approved these changes
LGTM

2018-03-14 17:59 UTC, wamisnet commented
ちゃんとくさんのタスクが積もってるのでとりあえずこの件はクローズして、全体確認の際にでも確認してもらう。

2018-03-14 17:59 UTC, merged