Tipsを追加
Nefry-Community/TutorialBook pull request #34
Opened 2018-03-15 15:47 UTC by pokiiio

2018-03-16 16:38 UTC, pokiiio commented
Tipsを更新しました。ご確認のほどよろしくお願いします。

2018-03-21 11:14 UTC, wamisnet approved these changes

2018-03-21 11:14 UTC, wamisnet commented on articles/20Tips.re
Macユーザの場合はこちらの情報も参考にしてください。（@<href>{http://relativelayout.hatenablog.com/entry/2017/09/01/223718}）

この記事の紹介を入れたいですね

2018-03-21 16:38 UTC, wamisnet commented on articles/20Tips.re
@pokiiio これどう思います？？

2018-03-21 16:38 UTC, wamisnet approved these changes

2018-03-21 16:40 UTC, wamisnet requested changes
コメント残したところを確認してください

2018-03-24 06:42 UTC, pokiiio commented on articles/20Tips.re
紹介して良ければ！いれます！

2018-03-26 09:18 UTC, wamisnet approved these changes

2018-03-26 09:18 UTC, wamisnet commented on articles/20Tips.re
@pokiiio Macの場合はドライバーを変更するといいって追記していただけるといいかなって思います。
Windowsの場合はArduinoIDEをインストールするときにインストールされるので

2018-04-07 03:35 UTC, merged