00start
Nefry-Community/TutorialBook pull request #39
Opened 2018-04-05 03:14 UTC by 1ft-seabass

00start対応

2018-04-05 17:12 UTC, wamisnet requested changes

2018-04-05 17:12 UTC, wamisnet commented on articles/00start.re
> +みなさん、ハードウエアのほうで作ってみたことありますか？
ハードウエアのほう？タイプミス？？

2018-04-05 17:12 UTC, wamisnet commented on articles/00start.re
> +ソフトウェアでつくることも楽しいものですが、ディスプレイから飛び出して、現実を直接知覚しダイナミックに動かせるのがハードウェアの面白いところです。
いきなり作るのが楽しいとなっているが、ちょっと具体例があった方がわかりやすいのかもしれないです！

2018-04-05 17:12 UTC, wamisnet commented on articles/00start.re
> +本来、ハードウェアの指す範囲は広いですが、電子工作におけるハードウェアの視点からいえば、まず、モーターによる動き、ブザーのような音、電球（LED）による光など手ざわりに直結した動作を作ることができることは面白いです。
面白いですと言い切ってますけど対象読者は興味はあるけど面白いと共感してもらうために上にも上げましたけど京急の例を挙げるなど、具体例なりどんなことができるのかがあるとよいのかなと思います。

2018-04-05 17:12 UTC, wamisnet commented on articles/00start.re
> +このように、ハードウェアを使うことで、ソフトウェアとはまた違った方向から、現実世界の「つくること」にアプローチできるのは魅力的です。
このように、ハードウェアを使うことで、ソフトウェアとはまた違った方向から、現実世界の「つくること」にアプローチできるのは魅力的です。
↓
「ハードウエアを使うことで現実世界をハックすることができる」みたいな表現の方がわかりやすいかも？
気持ちは伝わるのですけど、なんか遠回りな表現をしている気がして…

2018-04-05 17:12 UTC, wamisnet commented on articles/00start.re
> +実際、この章を書いている私も、何度も踏み入れようとしてうまくいかなかった経験があります。
（筆者でも難しかったみたいなの私はいいなと思います。

2018-04-05 17:12 UTC, wamisnet commented on articles/00start.re
> +さて、このハードウェア。以前ですと、電流の流れに関することや、それを発展させた回路図について、はたまたハンダ付けに代表されるしっかりと部品をあつかう技術など、さまざまな事柄が絶妙に組み合わさってこそはじめて踏み入れることができる領域でした。
箇条書きでまとめた方がわかりやすいかもしれないですね

- コンデンサや抵抗など電子の基礎知識
- 部品の接続をするために必要な回路図の理解
- 部品選択のために必要なデータシートの読み方
- 半田付け等の基礎技術

田中さんの記載してくれた内容をベースにぱっと思いつくものを並べてみました。

2018-04-05 17:12 UTC, wamisnet commented on articles/00start.re
> +そして、Groveやブレッドボードといった技術によって部品をあつかう技術についても、ハンダ付けをしなくても安全に電子工作を体験できる仕組みも整ってきていることも心強いポイントでしょう。
ハンダ付けをしなくても安全に電子工作→ハンダ付けをしなくても手軽に電子工作

安全というより手軽さなのかなという気がします。
半田付けがいらないというのを安全と考えるのもわからなくないですけど、そっちのメリットよりプロトタイピングが手軽＆簡単になったほうが大きいのかなと思います。これはどちらでもいい気はしますのでコメントください。

2018-04-05 17:12 UTC, wamisnet commented on articles/00start.re
> +今までハードウェアの中で完結していたデータが、インターネットの力とうまく混ぜ合わせることで、情報の世界に飛び出し生き生きと活用されるようになっていますが、Nefry BTでも使われているESP32チップは、Arduinoで手軽にインターネットにつながる仕組みまでも備えています！
後ろの章でNefryについて詳しく話しているのでここで話すべきはNefryというより、ネットにつながるからどうなのかを伝える方がよいかなと思います

2018-04-06 03:16 UTC, 1ft-seabass commented on articles/00start.re
> +みなさん、ハードウエアのほうで作ってみたことありますか？
「のほう」書き癖でついつい書いちゃうやつで、タイプミスです。直します～。

2018-04-06 03:17 UTC, 1ft-seabass commented on articles/00start.re
> +ソフトウェアでつくることも楽しいものですが、ディスプレイから飛び出して、現実を直接知覚しダイナミックに動かせるのがハードウェアの面白いところです。
了解です！サラッと流したほうがいいかなと思ったんですが、手厚くしますね。

2018-04-06 03:19 UTC, 1ft-seabass commented on articles/00start.re
> +本来、ハードウェアの指す範囲は広いですが、電子工作におけるハードウェアの視点からいえば、まず、モーターによる動き、ブザーのような音、電球（LED）による光など手ざわりに直結した動作を作ることができることは面白いです。
はい。具体的に行きます。

* インターネットの情報を現実に落とし込む　→　京急例
* センサーで感知したものを集めて表示する　→　明星和楽例など

と添えるつもりです。水やりでもいいですね。

2018-04-06 03:19 UTC, 1ft-seabass commented on articles/00start.re
> +このように、ハードウェアを使うことで、ソフトウェアとはまた違った方向から、現実世界の「つくること」にアプローチできるのは魅力的です。
ちょっと遠回りですね。「ハードウエアを使うことで現実世界をハックすることができる」に直します。

2018-04-06 03:19 UTC, 1ft-seabass commented on articles/00start.re
> +実際、この章を書いている私も、何度も踏み入れようとしてうまくいかなかった経験があります。
👍

2018-04-06 03:20 UTC, 1ft-seabass commented on articles/00start.re
> +さて、このハードウェア。以前ですと、電流の流れに関することや、それを発展させた回路図について、はたまたハンダ付けに代表されるしっかりと部品をあつかう技術など、さまざまな事柄が絶妙に組み合わさってこそはじめて踏み入れることができる領域でした。
ですね。箇条書きで行きましょう。わたしも正直わみさんほど分かってないので案をいただき助かりますー。

2018-04-06 03:20 UTC, 1ft-seabass commented on articles/00start.re
> +そして、Groveやブレッドボードといった技術によって部品をあつかう技術についても、ハンダ付けをしなくても安全に電子工作を体験できる仕組みも整ってきていることも心強いポイントでしょう。
手軽押しでいきましょう。

2018-04-06 03:21 UTC, 1ft-seabass commented on articles/00start.re
> +今までハードウェアの中で完結していたデータが、インターネットの力とうまく混ぜ合わせることで、情報の世界に飛び出し生き生きと活用されるようになっていますが、Nefry BTでも使われているESP32チップは、Arduinoで手軽にインターネットにつながる仕組みまでも備えています！
了解です。ちょっと唐突で悩ましいなというところは書いてても感じたので、削るか、別アプローチで書きます。

2018-04-07 04:00 UTC, merged